export const clientConfig = {
  brand: {
    name: 'Jenga Electronics',
    tagline: "Kenya's Premier Electronics & Appliances Store",
    logo: '/brand/logo.svg',
    favicon: '/brand/favicon.png',
    colors: {
      primary: '#0066CC',
      primaryRgb: '0 102 204',
      primaryLight: '#e0edff',
      primaryLightRgb: '224 237 255',
      primaryDark: '#004fa3',
      primaryDarkRgb: '0 79 163',
      secondary: '#FF6600',
      accent: '#00AA66',
      background: '#f8fafc',
      surface: '255 255 255',
      surfaceMuted: '#f1f5f9',
    },
  },
  business: {
    currency: 'KES',
    currencySymbol: 'Ksh',
    taxRate: 16,
    phone: '+254 700 000000',
    whatsapp: '254700000000',
    email: 'support@jenga.co.ke',
    address: 'Westlands, Nairobi, Kenya',
    freeDeliveryThreshold: 3000,
    standardDelivery: 300,
    expressDelivery: 500,
  },
  features: {
    wishlist: true,
    compare: true,
    reviews: true,
    cod: true,
    multiVendor: true,
    whatsapp: true,
    blog: false,
    bnpl: true,
  },
  payments: {
    mpesa: { enabled: true, paybill: '247247' },
    card: { enabled: true, provider: 'pesapal' },
    cod: { enabled: true, maxOrderValue: 50000 },
  },
  categories: [
    { slug: 'smartphones', name: 'Smartphones', icon: 'Smartphone', color: '#0066CC' },
    { slug: 'laptops', name: 'Laptops', icon: 'Laptop', color: '#7C3AED' },
    { slug: 'televisions', name: 'TVs', icon: 'Tv', color: '#DC2626' },
    { slug: 'fridges', name: 'Fridges', icon: 'Wind', color: '#059669' },
    { slug: 'washing-machines', name: 'Washing Machines', icon: 'Waves', color: '#0891B2' },
    { slug: 'audio', name: 'Audio', icon: 'Speaker', color: '#D97706' },
    { slug: 'cameras', name: 'Cameras', icon: 'Camera', color: '#BE185D' },
    { slug: 'accessories', name: 'Accessories', icon: 'Zap', color: '#65A30D' },
  ],
  seo: {
    siteName: 'Jenga Electronics',
    titleTemplate: '%s | Jenga Electronics',
    description: 'Shop smartphones, laptops, TVs, fridges and appliances. Pay via M-PESA. Fast delivery across Kenya.',
    twitterHandle: '@JengaElectro',
  },
}

export type ClientConfig = typeof clientConfig
