export const clientConfig = {
  brand: {
    name: 'Msingi Store',
    tagline: 'The African Commerce Platform — Live Demo Storefront',
    logo: '/brand/logo.svg',
    favicon: '/brand/favicon.png',
    platformName: 'Msingi',
    platformUrl: 'https://msingios.vercel.app',
    demoNotice: 'This is a live demo of the Msingi commerce platform.',
    colors: {
      primary: '#6366F1',
      primaryRgb: '99 102 241',
      primaryLight: '#EEF2FF',
      primaryLightRgb: '238 242 255',
      primaryDark: '#4338CA',
      primaryDarkRgb: '67 56 202',
      secondary: '#F59E0B',
      accent: '#10B981',
      background: '#f8fafc',
      surface: '255 255 255',
      surfaceMuted: '#f1f5f9',
    },
  },
  business: {
    currency: 'KES',
    currencySymbol: 'Ksh',
    taxRate: 16,
    phone: '+254 700 000000',
    whatsapp: '254700000000',
    email: 'demo@msingi.dev',
    address: 'Nairobi, Kenya',
    freeDeliveryThreshold: 3000,
    standardDelivery: 300,
    expressDelivery: 500,
  },
  features: {
    wishlist: true,
    compare: true,
    reviews: true,
    cod: true,
    multiVendor: true,
    whatsapp: true,
    blog: false,
    bnpl: true,
  },
  payments: {
    mpesa: { enabled: true, paybill: '247247' },
    card: { enabled: true, provider: 'pesapal' },
    cod: { enabled: true, maxOrderValue: 50000 },
  },
  categories: [
    { slug: 'smartphones', name: 'Smartphones', icon: 'Smartphone', color: '#6366F1' },
    { slug: 'laptops', name: 'Laptops', icon: 'Laptop', color: '#8B5CF6' },
    { slug: 'televisions', name: 'TVs', icon: 'Tv', color: '#EC4899' },
    { slug: 'fridges', name: 'Fridges', icon: 'Wind', color: '#10B981' },
    { slug: 'washing-machines', name: 'Washing Machines', icon: 'Waves', color: '#0EA5E9' },
    { slug: 'audio', name: 'Audio', icon: 'Speaker', color: '#F59E0B' },
    { slug: 'cameras', name: 'Cameras', icon: 'Camera', color: '#EF4444' },
    { slug: 'accessories', name: 'Accessories', icon: 'Zap', color: '#14B8A6' },
  ],
  seo: {
    siteName: 'Msingi Store',
    titleTemplate: '%s | Msingi Store',
    description: 'Live demo storefront powered by Msingi — the African commerce platform. Shop electronics, pay via M-PESA, delivered across Kenya.',
    twitterHandle: '@MsingiOS',
  },
}

export type ClientConfig = typeof clientConfig
