export interface Seller {
  id: string
  name: string
  verified: boolean
  isVerified: boolean
  badge: 'basic' | 'verified' | 'premium' | 'authorized'
  rating: number
  salesCount: number
  productCount: number
  totalRevenue: number
  location: string
  responseTime: string
  description: string
}

export interface Product {
  id: string
  name: string
  slug: string
  brand: string
  category: string
  price: number
  originalPrice?: number
  discount?: number
  images: string[]
  rating: number
  reviewCount: number
  inStock: boolean
  stockCount: number
  description: string
  features: string[]
  specifications: Record<string, string>
  warranty: string
  requiresInstallation: boolean
  installationFee?: number
  seller: Seller
  tags: string[]
  bnplAvailable: boolean
  monthlyInstallment?: number
  isFlashSale?: boolean
  isFeatured?: boolean
  isTrending?: boolean
  deliveryDays: string
}

export interface Category {
  id: string
  name: string
  slug: string
  iconName: string
  productCount: number
  color: string
  description: string
}

export interface Review {
  id: string
  productId: string
  author: string
  location: string
  rating: number
  title: string
  body: string
  date: string
  verified: boolean
  helpful: number
  imageUrl?: string
}

export interface Order {
  id: string
  customerName: string
  customerPhone: string
  items: { productId: string; name: string; quantity: number; price: number; image: string }[]
  total: number
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled'
  paymentMethod: 'mpesa' | 'cash' | 'card' | 'bnpl'
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded'
  deliveryAddress: string
  county: string
  createdAt: string
  mpesaRef?: string
  courierName?: string
  trackingNumber?: string
}

export const sellers: Seller[] = [
  { id: 's1', name: 'Samsung Kenya Official', verified: true, isVerified: true, badge: 'authorized', rating: 4.9, salesCount: 3240, productCount: 48, totalRevenue: 4500000, location: 'Nairobi CBD', responseTime: '< 1 hour', description: 'Official Samsung Kenya store — genuine products with full warranty.' },
  { id: 's2', name: 'Avechi Electronics', verified: true, isVerified: true, badge: 'authorized', rating: 4.8, salesCount: 2190, productCount: 120, totalRevenue: 3200000, location: 'Westlands, Nairobi', responseTime: '< 2 hours', description: "Kenya's largest authorised electronics dealer with 10+ brands." },
  { id: 's3', name: 'Techmart Kenya', verified: true, isVerified: true, badge: 'premium', rating: 4.6, salesCount: 1560, productCount: 85, totalRevenue: 1800000, location: 'Mombasa Road', responseTime: '< 3 hours', description: 'Premium electronics and accessories for professionals.' },
  { id: 's4', name: 'Quickmart Electronics', verified: true, isVerified: true, badge: 'verified', rating: 4.5, salesCount: 890, productCount: 42, totalRevenue: 950000, location: 'Kisumu', responseTime: '< 4 hours', description: 'Affordable electronics for Western Kenya.' },
  { id: 's5', name: 'iStore Kenya', verified: true, isVerified: true, badge: 'authorized', rating: 4.9, salesCount: 1870, productCount: 30, totalRevenue: 2700000, location: 'The Junction Mall', responseTime: '< 1 hour', description: 'Authorised Apple Premium Reseller in Kenya.' },
]

export const categories: Category[] = [
  { id: '1', name: 'Smartphones', slug: 'smartphones', iconName: 'Smartphone', productCount: 245, color: 'from-blue-500 to-blue-700', description: 'Latest phones from top brands' },
  { id: '2', name: 'Laptops', slug: 'laptops', iconName: 'Laptop', productCount: 132, color: 'from-violet-500 to-violet-700', description: 'Laptops for work & gaming' },
  { id: '3', name: 'Televisions', slug: 'televisions', iconName: 'Tv', productCount: 89, color: 'from-cyan-500 to-cyan-700', description: 'Smart TVs & home cinema' },
  { id: '4', name: 'Fridges', slug: 'fridges', iconName: 'Thermometer', productCount: 67, color: 'from-teal-500 to-teal-700', description: 'Refrigerators & freezers' },
  { id: '5', name: 'Washing Machines', slug: 'washing-machines', iconName: 'RefreshCw', productCount: 45, color: 'from-indigo-500 to-indigo-700', description: 'Front load & top load' },
  { id: '6', name: 'Audio', slug: 'audio', iconName: 'Headphones', productCount: 178, color: 'from-pink-500 to-pink-700', description: 'Headphones, earbuds & speakers' },
  { id: '7', name: 'Tablets', slug: 'tablets', iconName: 'Tablet', productCount: 54, color: 'from-orange-500 to-orange-700', description: 'Tablets for work & entertainment' },
  { id: '8', name: 'Cookers', slug: 'cookers', iconName: 'Flame', productCount: 38, color: 'from-red-500 to-red-700', description: 'Gas cookers & electric stoves' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    brand: 'Samsung',
    category: 'smartphones',
    price: 139999,
    originalPrice: 159999,
    discount: 12,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600&auto=format&q=80',
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&q=80',
    ],
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    stockCount: 15,
    description: 'The Samsung Galaxy S24 Ultra redefines flagship performance. Powered by Snapdragon 8 Gen 3, its 200MP quad-camera and built-in S Pen make it the ultimate productivity and creativity companion.',
    features: [
      '200MP quad-camera with 100× Space Zoom',
      'Built-in S Pen with zero latency',
      'Snapdragon 8 Gen 3 for Galaxy',
      '6.8" Dynamic AMOLED 2X, 120Hz ProMotion',
      '5000mAh with 45W fast charging + 15W wireless',
      'Galaxy AI features (Circle to Search, Live Translate)',
    ],
    specifications: {
      'Display': '6.8" Dynamic AMOLED 2X, 3088×1440',
      'Processor': 'Snapdragon 8 Gen 3 for Galaxy',
      'RAM': '12GB',
      'Storage': '256GB / 512GB / 1TB',
      'Main Camera': '200MP + 12MP UW + 50MP 5× + 10MP 3×',
      'Front Camera': '12MP',
      'Battery': '5000mAh',
      'Charging': '45W wired, 15W wireless',
      'OS': 'Android 14, One UI 6.1',
      'Weight': '232g',
      'Colors': 'Titanium Black, Gray, Violet, Yellow',
    },
    warranty: '12 months Samsung Kenya official warranty',
    requiresInstallation: false,
    seller: sellers[0],
    tags: ['5G', 'S Pen', 'AI Camera', 'Flagship', '200MP'],
    bnplAvailable: true,
    monthlyInstallment: 11667,
    isFeatured: true,
    isTrending: true,
    deliveryDays: '1-2 business days',
  },
  {
    id: '2',
    name: 'iPhone 15 Pro',
    slug: 'iphone-15-pro',
    brand: 'Apple',
    category: 'smartphones',
    price: 174999,
    originalPrice: 189999,
    discount: 8,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&q=80',
    ],
    rating: 4.9,
    reviewCount: 189,
    inStock: true,
    stockCount: 8,
    description: 'The iPhone 15 Pro features a lightweight titanium design and the powerful A17 Pro chip — the first 3nm chip in a smartphone. Its 48MP main camera shoots ProRAW and ProRes video.',
    features: [
      'A17 Pro chip – first 3nm mobile chip',
      'Titanium frame with matte glass back',
      '48MP main + 12MP ultrawide + 12MP 3× telephoto',
      'ProMotion 6.1" Super Retina XDR OLED',
      'Action button – fully customizable',
      'USB-C with USB 3 speeds',
    ],
    specifications: {
      'Display': '6.1" LTPO Super Retina XDR, 2556×1179',
      'Chip': 'A17 Pro (3nm)',
      'RAM': '8GB',
      'Storage': '128GB / 256GB / 512GB / 1TB',
      'Camera': '48MP + 12MP UW + 12MP 3× Tele',
      'Front': '12MP TrueDepth',
      'Battery': 'Up to 23h video playback',
      'Connectivity': 'USB-C USB 3, Wi-Fi 6E, 5G',
      'OS': 'iOS 17',
      'Weight': '187g',
    },
    warranty: '12 months Apple Kenya warranty + AppleCare+ option',
    requiresInstallation: false,
    seller: sellers[4],
    tags: ['A17 Pro', 'Titanium', 'ProRAW', 'ProRes', 'Premium'],
    bnplAvailable: true,
    monthlyInstallment: 14583,
    isFeatured: false,
    isTrending: true,
    deliveryDays: '1-2 business days',
  },
  {
    id: '3',
    name: 'Infinix Hot 40 Pro',
    slug: 'infinix-hot-40-pro',
    brand: 'Infinix',
    category: 'smartphones',
    price: 18999,
    originalPrice: 26999,
    discount: 30,
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&q=80',
    ],
    rating: 4.3,
    reviewCount: 412,
    inStock: true,
    stockCount: 67,
    description: 'Infinix Hot 40 Pro delivers excellent value with a 6.78" FHD+ display, 108MP camera, and 45W fast charging at an unbeatable price. Perfect for university students and budget-conscious buyers.',
    features: [
      '6.78" FHD+ 90Hz display',
      '108MP main camera',
      '5000mAh battery with 45W fast charging',
      'Helio G99 processor',
      'Dual SIM + expandable storage',
      '3.5mm headphone jack',
    ],
    specifications: {
      'Display': '6.78" IPS LCD, FHD+, 90Hz',
      'Processor': 'MediaTek Helio G99',
      'RAM': '8GB (+ 8GB virtual)',
      'Storage': '256GB',
      'Camera': '108MP + 2MP depth',
      'Front': '32MP',
      'Battery': '5000mAh, 45W',
      'OS': 'Android 13, XOS 13',
      'Weight': '193g',
    },
    warranty: '12 months Infinix Kenya warranty',
    requiresInstallation: false,
    seller: sellers[2],
    tags: ['Budget', '108MP', '45W Charging', 'Student Pick'],
    bnplAvailable: false,
    isFlashSale: true,
    isTrending: false,
    deliveryDays: '2-3 business days',
  },
  {
    id: '4',
    name: 'Apple MacBook Air M3',
    slug: 'macbook-air-m3',
    brand: 'Apple',
    category: 'laptops',
    price: 159999,
    originalPrice: 174999,
    discount: 9,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&q=80',
    ],
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    stockCount: 12,
    description: 'The MacBook Air with M3 chip is the world\'s best consumer laptop. Fanless, silent, and lasting up to 18 hours, it delivers desktop-class performance in a featherlight 1.24kg frame.',
    features: [
      'Apple M3 chip (8-core CPU, 10-core GPU)',
      'Up to 18 hours battery life',
      '13.6" Liquid Retina display, P3 wide color',
      'Silent fanless design, 1.24kg',
      'MagSafe charging + 2× Thunderbolt 4',
      'macOS Sonoma with Apple Intelligence',
    ],
    specifications: {
      'Display': '13.6" Liquid Retina, 2560×1664, P3',
      'Chip': 'Apple M3 (3nm)',
      'CPU Cores': '8-core',
      'GPU Cores': '10-core',
      'RAM': '8GB / 16GB / 24GB',
      'Storage': '256GB / 512GB / 1TB / 2TB SSD',
      'Battery': 'Up to 18h',
      'Weight': '1.24kg',
      'Ports': 'MagSafe 3, 2× Thunderbolt 4, 3.5mm',
      'OS': 'macOS Sonoma',
    },
    warranty: '12 months Apple warranty + AppleCare+ available',
    requiresInstallation: false,
    seller: sellers[4],
    tags: ['M3 Chip', 'Fanless', '18h Battery', 'Ultralight'],
    bnplAvailable: true,
    monthlyInstallment: 13333,
    isFeatured: true,
    isTrending: true,
    deliveryDays: '1-2 business days',
  },
  {
    id: '5',
    name: 'HP Pavilion 15 Laptop',
    slug: 'hp-pavilion-15',
    brand: 'HP',
    category: 'laptops',
    price: 64999,
    originalPrice: 74999,
    discount: 13,
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&q=80',
    ],
    rating: 4.4,
    reviewCount: 287,
    inStock: true,
    stockCount: 24,
    description: 'HP Pavilion 15 is the perfect everyday laptop for work, study, and entertainment. Powered by Intel Core i5 12th Gen with a vibrant FHD IPS display and a full day battery.',
    features: [
      'Intel Core i5-1235U 12th Gen',
      '15.6" FHD IPS anti-glare display',
      '8GB DDR4 RAM, upgradeable to 32GB',
      '512GB NVMe SSD',
      'Intel Iris Xe integrated graphics',
      'HP Fast Charge – 50% in 45 minutes',
    ],
    specifications: {
      'Display': '15.6" FHD IPS (1920×1080)',
      'Processor': 'Intel Core i5-1235U (12th Gen)',
      'RAM': '8GB DDR4-3200',
      'Storage': '512GB PCIe NVMe SSD',
      'Graphics': 'Intel Iris Xe',
      'Battery': '41Wh, ~8h',
      'Weight': '1.75kg',
      'Ports': 'USB-C, 2× USB-A, HDMI, SD, 3.5mm',
      'OS': 'Windows 11 Home',
    },
    warranty: '1 year HP international warranty',
    requiresInstallation: false,
    seller: sellers[1],
    tags: ['Intel i5', 'Windows 11', 'Student', 'Work Laptop'],
    bnplAvailable: true,
    monthlyInstallment: 5417,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-3 business days',
  },
  {
    id: '6',
    name: 'Samsung 55" QLED 4K Smart TV',
    slug: 'samsung-55-qled-4k-tv',
    brand: 'Samsung',
    category: 'televisions',
    price: 89999,
    originalPrice: 109999,
    discount: 18,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f4834b?w=600&auto=format&q=80',
    ],
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    stockCount: 9,
    description: 'Samsung 55" QLED TV with Quantum Dot technology delivers 100% color volume for stunning picture quality. Smart TV with built-in Netflix, YouTube, and DSTV Now.',
    features: [
      'Quantum Dot technology – 100% color volume',
      '4K UHD resolution with HDR10+',
      'Tizen Smart TV – Netflix, YouTube, Prime',
      'Dolby Digital+ sound',
      'Motion Rate 200 – sports & gaming ready',
      'AirPlay 2 & SmartThings compatible',
    ],
    specifications: {
      'Screen Size': '55"',
      'Resolution': '4K UHD (3840×2160)',
      'Panel': 'QLED',
      'HDR': 'HDR10+',
      'Smart Platform': 'Tizen',
      'HDMI Ports': '4',
      'USB Ports': '2',
      'Audio': '20W, Dolby Digital+',
      'Dimensions (with stand)': '124.3×78.4×26.5cm',
    },
    warranty: '2 years Samsung Kenya warranty + free installation',
    requiresInstallation: true,
    installationFee: 0,
    seller: sellers[0],
    tags: ['QLED', '4K', 'Smart TV', 'Netflix', 'Tizen'],
    bnplAvailable: true,
    monthlyInstallment: 7500,
    isFeatured: true,
    isTrending: false,
    deliveryDays: '2-4 business days',
  },
  {
    id: '7',
    name: 'Hisense 43" FHD Smart TV',
    slug: 'hisense-43-fhd-smart-tv',
    brand: 'Hisense',
    category: 'televisions',
    price: 32999,
    originalPrice: 39999,
    discount: 18,
    images: [
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&q=80',
    ],
    rating: 4.3,
    reviewCount: 356,
    inStock: true,
    stockCount: 31,
    description: 'Hisense 43" Smart TV running VIDAA OS with built-in Netflix and YouTube. Full HD display, DTS virtual-X sound, and a slim bezel design for any living room.',
    features: [
      'VIDAA Smart OS with voice search',
      'Full HD 1080p display',
      'DTS Virtual-X surround sound',
      'Dolby Audio',
      'Triple tuner (DVB-T2/S2/C)',
      'Slim bezel design',
    ],
    specifications: {
      'Screen Size': '43"',
      'Resolution': 'Full HD (1920×1080)',
      'Smart Platform': 'VIDAA',
      'HDMI': '3',
      'USB': '2',
      'Audio': '16W',
      'Tuner': 'DVB-T2/S2/C',
    },
    warranty: '2 years Hisense Kenya warranty',
    requiresInstallation: true,
    installationFee: 500,
    seller: sellers[3],
    tags: ['FHD', 'Smart TV', 'VIDAA', 'Budget TV', 'Netflix'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-4 business days',
  },
  {
    id: '8',
    name: 'LG 385L Double Door Fridge',
    slug: 'lg-385l-double-door-fridge',
    brand: 'LG',
    category: 'fridges',
    price: 54999,
    originalPrice: 64999,
    discount: 15,
    images: [
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&auto=format&q=80',
    ],
    rating: 4.6,
    reviewCount: 143,
    inStock: true,
    stockCount: 6,
    description: 'LG 385L double door refrigerator with Smart Inverter Compressor for energy efficiency. LinearCooling keeps food fresh 2× longer, and Door Cooling+ ensures even temperature throughout.',
    features: [
      'Smart Inverter Compressor – 10-year warranty',
      'LinearCooling: keeps food fresh 2× longer',
      'Door Cooling+ for fast and even cooling',
      'Hygiene Fresh+ multi-air flow system',
      '385L total capacity (270L fridge + 115L freezer)',
      'A++ Energy Rating',
    ],
    specifications: {
      'Capacity': '385L (270L + 115L)',
      'Energy Rating': 'A++',
      'Compressor': 'Smart Inverter',
      'Freezer': 'Bottom Freezer',
      'Color': 'Silver / Dark Graphite',
      'Dimensions': '70×67.5×182cm',
      'Weight': '78kg',
    },
    warranty: '1 year parts & labor, 10 years compressor warranty',
    requiresInstallation: true,
    installationFee: 1500,
    seller: sellers[1],
    tags: ['Inverter', 'Energy Efficient', 'Bottom Freezer', 'Large Capacity'],
    bnplAvailable: true,
    monthlyInstallment: 4583,
    isFlashSale: true,
    isFeatured: true,
    isTrending: false,
    deliveryDays: '3-5 business days',
  },
  {
    id: '9',
    name: 'LG 9KG Front Load Washing Machine',
    slug: 'lg-9kg-front-load-washing-machine',
    brand: 'LG',
    category: 'washing-machines',
    price: 64999,
    originalPrice: 74999,
    discount: 13,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&q=80',
    ],
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
    stockCount: 11,
    description: 'LG 9kg front-load washing machine with AI DD (Direct Drive) technology learns fabric weight and softness for the optimal wash cycle every time. TurboWash 360° washes full loads in 39 minutes.',
    features: [
      'AI Direct Drive – learns your fabric type',
      'TurboWash 360° – full load in 39 minutes',
      'Steam technology removes 99.9% of allergens',
      '1400 RPM spin speed',
      'Eco Hybrid mode for energy savings',
      'Smart Diagnosis via LG ThinQ app',
    ],
    specifications: {
      'Capacity': '9kg',
      'Spin Speed': '1400 RPM',
      'Energy Rating': 'A+++',
      'Programs': '14',
      'Dimensions': '60×56×85cm',
      'Weight': '72kg',
      'Noise': '49dB wash, 74dB spin',
    },
    warranty: '2 years parts & labor, 10 years motor warranty',
    requiresInstallation: true,
    installationFee: 2000,
    seller: sellers[1],
    tags: ['AI DD', 'TurboWash', 'Steam', 'Front Load', 'Inverter'],
    bnplAvailable: true,
    monthlyInstallment: 5417,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '3-5 business days',
  },
  {
    id: '10',
    name: 'Bruhm 4-Burner Gas Cooker',
    slug: 'bruhm-4-burner-gas-cooker',
    brand: 'Bruhm',
    category: 'cookers',
    price: 16999,
    originalPrice: 21999,
    discount: 23,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&q=80',
    ],
    rating: 4.4,
    reviewCount: 267,
    inStock: true,
    stockCount: 44,
    description: 'Bruhm 60cm freestanding 4-burner gas cooker with electric oven and grill. Stainless steel finish, auto-ignition, and full safety cut-off valves on all burners.',
    features: [
      '4 gas burners with auto-ignition',
      '65L electric oven with grill',
      'Stainless steel finish',
      'Safety cut-off valve on all burners',
      'Removable cast iron pan supports',
      'Turbo grill for faster cooking',
    ],
    specifications: {
      'Burners': '4 gas (1 wok + 2 semi-rapid + 1 auxiliary)',
      'Oven Capacity': '65L',
      'Ignition': 'Auto-electric',
      'Fuel': 'LPG / Natural Gas',
      'Width': '60cm',
      'Material': 'Stainless Steel',
      'Warranty': '1 year',
    },
    warranty: '1 year Bruhm Kenya warranty',
    requiresInstallation: true,
    installationFee: 1000,
    seller: sellers[3],
    tags: ['Gas Cooker', '4 Burner', 'Electric Oven', 'Auto-ignition'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-4 business days',
  },
  {
    id: '11',
    name: 'Sony WH-1000XM5 Headphones',
    slug: 'sony-wh-1000xm5',
    brand: 'Sony',
    category: 'audio',
    price: 27999,
    originalPrice: 34999,
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&q=80',
    ],
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    stockCount: 18,
    description: 'Sony WH-1000XM5 – the gold standard of noise cancellation. Eight microphones and two processors deliver unmatched ANC. 30-hour battery life with quick charge. Crystal-clear calls with AI noise reduction.',
    features: [
      'Industry-leading noise cancellation – 8 microphones',
      '30h battery + 3h from 3-min quick charge',
      'Multipoint Bluetooth (connect 2 devices)',
      'Speak-to-Chat & Touch Sensor controls',
      '360 Reality Audio certified',
      '30mm driver with Sony DSEE Extreme',
    ],
    specifications: {
      'Driver Unit': '30mm',
      'Frequency': '4Hz–40,000Hz',
      'Bluetooth': '5.2, SBC/AAC/LDAC',
      'Battery': '30h (ANC on)',
      'Quick Charge': '3 min → 3h',
      'Weight': '250g',
      'Foldable': 'Yes',
      'Mic': '8 microphones',
    },
    warranty: '1 year Sony Kenya warranty',
    requiresInstallation: false,
    seller: sellers[2],
    tags: ['ANC', 'LDAC', '30h Battery', 'Premium Audio', 'Multipoint'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: true,
    deliveryDays: '1-3 business days',
  },
  {
    id: '12',
    name: 'JBL Charge 5 Portable Speaker',
    slug: 'jbl-charge-5',
    brand: 'JBL',
    category: 'audio',
    price: 11999,
    originalPrice: 16999,
    discount: 29,
    images: [
      'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&q=80',
    ],
    rating: 4.7,
    reviewCount: 441,
    inStock: true,
    stockCount: 53,
    description: 'JBL Charge 5 delivers powerful sound with a built-in power bank. IP67 waterproof and dustproof, it charges your devices while playing music for up to 20 hours.',
    features: [
      'IP67 waterproof and dustproof',
      '20h battery life',
      'USB-C power bank to charge your phone',
      'JBL PartyBoost – pair with multiple speakers',
      'Pure Bass with passive radiator',
      'Speakerphone with noise-cancelling mic',
    ],
    specifications: {
      'Output Power': '30W RMS',
      'Frequency': '65Hz–20kHz',
      'Bluetooth': '5.1',
      'Battery': '7500mAh (20h playback)',
      'Charging': 'USB-C, charges phone via USB-A',
      'Waterproof': 'IP67',
      'Weight': '960g',
    },
    warranty: '1 year JBL warranty',
    requiresInstallation: false,
    seller: sellers[2],
    tags: ['Waterproof', 'IP67', 'Power Bank', '20h Battery', 'PartyBoost'],
    bnplAvailable: false,
    isFlashSale: true,
    isTrending: false,
    deliveryDays: '1-3 business days',
  },
  {
    id: '13',
    name: 'Samsung Galaxy Tab S9',
    slug: 'samsung-galaxy-tab-s9',
    brand: 'Samsung',
    category: 'tablets',
    price: 69999,
    originalPrice: 79999,
    discount: 13,
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&q=80',
    ],
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    stockCount: 14,
    description: 'Samsung Galaxy Tab S9 with Dynamic AMOLED 2X display and IP68 water resistance. Snapdragon 8 Gen 2 powers seamless multitasking, DeX mode, and Samsung Notes with the S Pen included.',
    features: [
      '11" Dynamic AMOLED 2X, 120Hz, Vision Booster',
      'Snapdragon 8 Gen 2 for Galaxy',
      'IP68 water & dust resistance',
      'S Pen included (in-box)',
      'Samsung DeX desktop mode',
      '8400mAh battery with 45W fast charge',
    ],
    specifications: {
      'Display': '11" Dynamic AMOLED 2X, 2560×1600',
      'Processor': 'Snapdragon 8 Gen 2',
      'RAM': '8GB / 12GB',
      'Storage': '128GB / 256GB',
      'Camera': '13MP rear, 12MP ultra-wide front',
      'Battery': '8400mAh, 45W',
      'OS': 'Android 13, One UI 5.1',
      'Weight': '498g',
    },
    warranty: '1 year Samsung Kenya warranty',
    requiresInstallation: false,
    seller: sellers[0],
    tags: ['AMOLED', 'S Pen', 'IP68', 'DeX', 'Snapdragon 8 Gen 2'],
    bnplAvailable: true,
    monthlyInstallment: 5833,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '1-3 business days',
  },
  {
    id: '14',
    name: 'Apple AirPods Pro 2nd Gen',
    slug: 'airpods-pro-2',
    brand: 'Apple',
    category: 'audio',
    price: 29999,
    originalPrice: 34999,
    discount: 14,
    images: [
      'https://images.unsplash.com/photo-1590658006821-04f4008d5717?w=600&auto=format&q=80',
    ],
    rating: 4.8,
    reviewCount: 278,
    inStock: true,
    stockCount: 22,
    description: 'AirPods Pro 2 with H2 chip delivers 2× more noise cancellation than the original. Adaptive Transparency, Conversation Awareness, and 30h total battery with MagSafe charging case.',
    features: [
      '2× improved Active Noise Cancellation (H2 chip)',
      'Adaptive Transparency – hear what matters',
      'Personalized Spatial Audio',
      '30h total battery (6h AirPods + 24h case)',
      'MagSafe & wireless charging case',
      'IPX4 sweat and water resistance',
    ],
    specifications: {
      'Chip': 'Apple H2',
      'ANC': '2× improved',
      'Battery': '6h + 24h case = 30h total',
      'Connectivity': 'Bluetooth 5.3',
      'Charging': 'MagSafe, Lightning, Qi',
      'Water Resistance': 'IPX4',
      'Weight': '5.3g per earbud',
    },
    warranty: '1 year Apple warranty',
    requiresInstallation: false,
    seller: sellers[4],
    tags: ['H2 Chip', 'ANC', 'MagSafe', 'Spatial Audio', 'Premium'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: true,
    deliveryDays: '1-2 business days',
  },
  {
    id: '15',
    name: 'TCL 65" QLED 4K Smart TV',
    slug: 'tcl-65-qled-4k-tv',
    brand: 'TCL',
    category: 'televisions',
    price: 79999,
    originalPrice: 94999,
    discount: 16,
    images: [
      'https://images.unsplash.com/photo-1571415060716-baff7991ddc3?w=600&auto=format&q=80',
    ],
    rating: 4.5,
    reviewCount: 176,
    inStock: true,
    stockCount: 7,
    description: 'TCL 65" QLED TV with mini-LED backlighting and Dolby Vision IQ for cinema-quality picture. Google TV built-in gives access to 700,000+ movies and shows, with Google Assistant.',
    features: [
      'QLED with mini-LED backlight',
      'Dolby Vision IQ + Dolby Atmos',
      'Google TV – 700K+ apps',
      'ONKYO 2.0 sound system (30W)',
      'HDR Premium 1000',
      'HDMI 2.1 with 144Hz VRR for gaming',
    ],
    specifications: {
      'Screen Size': '65"',
      'Resolution': '4K UHD',
      'Panel': 'QLED Mini-LED',
      'HDR': 'Dolby Vision IQ, HDR10+',
      'Smart': 'Google TV',
      'Audio': '30W, Dolby Atmos',
      'HDMI': '4 (1× HDMI 2.1)',
      'Gaming': '144Hz VRR, ALLM, FreeSync',
    },
    warranty: '2 years TCL Kenya warranty',
    requiresInstallation: true,
    installationFee: 0,
    seller: sellers[3],
    tags: ['QLED', 'Google TV', 'Dolby Vision', '65 inch', '4K'],
    bnplAvailable: true,
    monthlyInstallment: 6667,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '3-5 business days',
  },
  {
    id: '16',
    name: 'Xiaomi Redmi Note 13 Pro+',
    slug: 'xiaomi-redmi-note-13-pro-plus',
    brand: 'Xiaomi',
    category: 'smartphones',
    price: 34999,
    originalPrice: 42999,
    discount: 19,
    images: [
      'https://images.unsplash.com/photo-1610945264803-c22b62d2a7b3?w=600&auto=format&q=80',
    ],
    rating: 4.5,
    reviewCount: 389,
    inStock: true,
    stockCount: 38,
    description: 'Xiaomi Redmi Note 13 Pro+ packs a 200MP OIS camera and 120W HyperCharge into a sleek curved AMOLED display. Achieves 0–100% charge in 19 minutes — perfect for the busy Kenyan on the go.',
    features: [
      '200MP OIS main camera',
      '120W HyperCharge – 0 to 100% in 19 minutes',
      '6.67" 1.5K AMOLED, 120Hz curved display',
      'MediaTek Dimensity 7200-Ultra',
      'IP68 water and dust resistance',
      '5000mAh battery',
    ],
    specifications: {
      'Display': '6.67" 1.5K AMOLED 120Hz',
      'Processor': 'Dimensity 7200-Ultra',
      'RAM': '12GB',
      'Storage': '256GB / 512GB',
      'Main Camera': '200MP OIS + 8MP UW + 2MP macro',
      'Front': '16MP',
      'Battery': '5000mAh, 120W',
      'OS': 'MIUI 14 / HyperOS',
      'Weight': '204g',
    },
    warranty: '1 year Xiaomi Kenya warranty',
    requiresInstallation: false,
    seller: sellers[2],
    tags: ['200MP', '120W Charging', 'AMOLED', 'IP68', 'Curved Display'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-3 business days',
  },

  // ─── Additional Smartphones ───────────────────────────────────────────────
  {
    id: '17',
    name: 'Samsung Galaxy A54 5G',
    slug: 'samsung-galaxy-a54-5g',
    brand: 'Samsung',
    category: 'smartphones',
    price: 39999,
    originalPrice: 49999,
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?w=600&auto=format&q=80',
    ],
    rating: 4.5,
    reviewCount: 312,
    inStock: true,
    stockCount: 42,
    description: 'Samsung Galaxy A54 5G delivers a premium experience at a mid-range price. A 50MP OIS camera, long-lasting 5000mAh battery, and 5G connectivity make it ideal for the modern Kenyan professional.',
    features: [
      '50MP OIS main camera with nightography',
      '6.4" FHD+ Super AMOLED 120Hz display',
      '5000mAh battery with 25W fast charge',
      '5G ready – future-proof connectivity',
      'IP67 water and dust resistance',
      'Samsung Knox security platform',
    ],
    specifications: {
      'Display': '6.4" FHD+ Super AMOLED 120Hz',
      'Processor': 'Exynos 1380 (5nm)',
      'RAM': '8GB',
      'Storage': '128GB / 256GB',
      'Main Camera': '50MP OIS + 12MP UW + 5MP macro',
      'Front Camera': '32MP',
      'Battery': '5000mAh, 25W',
      'OS': 'Android 13, One UI 5.1',
      'Weight': '202g',
    },
    warranty: '12 months Samsung Kenya warranty',
    requiresInstallation: false,
    seller: sellers[0],
    tags: ['5G', 'AMOLED', 'OIS Camera', 'IP67', 'Mid-range'],
    bnplAvailable: true,
    monthlyInstallment: 3333,
    isFeatured: true,
    isTrending: false,
    deliveryDays: '1-3 business days',
  },
  {
    id: '18',
    name: 'Tecno Camon 20 Pro 5G',
    slug: 'tecno-camon-20-pro-5g',
    brand: 'Tecno',
    category: 'smartphones',
    price: 23999,
    originalPrice: 29999,
    discount: 20,
    images: [
      'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&q=80',
    ],
    rating: 4.2,
    reviewCount: 528,
    inStock: true,
    stockCount: 76,
    description: 'Tecno Camon 20 Pro 5G is engineered for Kenyan photographers. A 108MP RGBW camera and 6.67" 10-bit AMOLED display at an incredibly accessible price point — the best camera value in Kenya.',
    features: [
      '108MP RGBW sensor main camera',
      '6.67" 10-bit AMOLED curved display',
      '5G connectivity on Dimensity 8050',
      '5000mAh with 33W fast charging',
      'Dual SIM + expandable microSD',
      'Portrait Master AI for perfect selfies',
    ],
    specifications: {
      'Display': '6.67" 10-bit AMOLED 120Hz',
      'Processor': 'MediaTek Dimensity 8050',
      'RAM': '8GB',
      'Storage': '256GB',
      'Main Camera': '108MP + 13MP UW + 2MP depth',
      'Front Camera': '50MP',
      'Battery': '5000mAh, 33W',
      'OS': 'Android 13, HiOS 13',
      'Weight': '195g',
    },
    warranty: '1 year Tecno Kenya warranty',
    requiresInstallation: false,
    seller: sellers[3],
    tags: ['5G', '108MP', 'AMOLED', 'Budget-Premium', 'Kenya Brand'],
    bnplAvailable: false,
    isFlashSale: true,
    isFeatured: false,
    isTrending: true,
    deliveryDays: '2-3 business days',
  },
  {
    id: '19',
    name: 'Google Pixel 7a',
    slug: 'google-pixel-7a',
    brand: 'Google',
    category: 'smartphones',
    price: 54999,
    originalPrice: 62999,
    discount: 13,
    images: [
      'https://images.unsplash.com/photo-1607936854279-55e8a4c64888?w=600&auto=format&q=80',
    ],
    rating: 4.6,
    reviewCount: 217,
    inStock: true,
    stockCount: 19,
    description: 'Google Pixel 7a brings the Tensor G2 chip and guaranteed 5 years of Android updates. Best-in-class computational photography, real-time call screening, and Google AI features at a mid-range price.',
    features: [
      'Google Tensor G2 chip – AI-powered',
      '64MP main + 13MP ultrawide camera',
      '5 years of OS and security updates',
      'Google Assistant with call screening',
      'Adaptive battery + 90Hz OLED display',
      'IP67 water resistance',
    ],
    specifications: {
      'Display': '6.1" FHD+ OLED 90Hz',
      'Chip': 'Google Tensor G2',
      'RAM': '8GB',
      'Storage': '128GB',
      'Camera': '64MP OIS + 13MP UW',
      'Front': '13MP',
      'Battery': '4385mAh, 18W',
      'OS': 'Android 13 → 14',
      'Weight': '193g',
    },
    warranty: '1 year Google warranty',
    requiresInstallation: false,
    seller: sellers[1],
    tags: ['Tensor G2', 'Google AI', '5-year Updates', 'OLED', 'IP67'],
    bnplAvailable: true,
    monthlyInstallment: 4583,
    isFeatured: false,
    isTrending: true,
    deliveryDays: '2-4 business days',
  },

  // ─── Additional Laptops ───────────────────────────────────────────────────
  {
    id: '20',
    name: 'Lenovo ThinkPad E14 Gen 4',
    slug: 'lenovo-thinkpad-e14-gen4',
    brand: 'Lenovo',
    category: 'laptops',
    price: 79999,
    originalPrice: 94999,
    discount: 16,
    images: [
      'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&q=80',
    ],
    rating: 4.6,
    reviewCount: 183,
    inStock: true,
    stockCount: 17,
    description: 'Lenovo ThinkPad E14 Gen 4 is the definitive business laptop for Kenyan professionals. AMD Ryzen 7 5825U delivers class-leading multi-core performance, with 16h battery and MIL-SPEC durability.',
    features: [
      'AMD Ryzen 7 5825U – 8-core powerhouse',
      '14" IPS FHD anti-glare display',
      '16GB DDR4 RAM + 512GB NVMe SSD',
      'ThinkPad keyboard – industry best',
      'MIL-SPEC 810H durability certified',
      'Fingerprint reader + IR camera (Windows Hello)',
    ],
    specifications: {
      'Display': '14" FHD IPS (1920×1080) 300 nits',
      'Processor': 'AMD Ryzen 7 5825U (Zen 3)',
      'RAM': '16GB DDR4-3200',
      'Storage': '512GB PCIe NVMe SSD',
      'Graphics': 'AMD Radeon Integrated',
      'Battery': '57Wh, up to 16h',
      'Weight': '1.65kg',
      'Ports': 'USB-C (PD), 2× USB-A, HDMI, RJ45, 3.5mm',
      'OS': 'Windows 11 Pro',
    },
    warranty: '1 year Lenovo Kenya carry-in warranty',
    requiresInstallation: false,
    seller: sellers[1],
    tags: ['Business Laptop', 'Ryzen 7', 'ThinkPad', 'MIL-SPEC', '16h Battery'],
    bnplAvailable: true,
    monthlyInstallment: 6667,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-4 business days',
  },
  {
    id: '21',
    name: 'ASUS TUF Gaming F15',
    slug: 'asus-tuf-gaming-f15',
    brand: 'ASUS',
    category: 'laptops',
    price: 109999,
    originalPrice: 129999,
    discount: 15,
    images: [
      'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&auto=format&q=80',
    ],
    rating: 4.7,
    reviewCount: 241,
    inStock: true,
    stockCount: 11,
    description: 'ASUS TUF Gaming F15 pairs an Intel Core i7-12700H with NVIDIA RTX 3060 for uncompromising gaming performance. The 144Hz IPS display and military-grade build make it the best gaming laptop under KES 120K.',
    features: [
      'Intel Core i7-12700H (12th Gen, 14-core)',
      'NVIDIA GeForce RTX 3060 6GB GDDR6',
      '15.6" FHD 144Hz IPS display',
      '16GB DDR5 RAM, 512GB NVMe SSD',
      'MIL-SPEC MIL-STD-810H tested',
      'Advanced cooling with 3 fans + 5 heatpipes',
    ],
    specifications: {
      'Display': '15.6" FHD IPS 144Hz',
      'Processor': 'Intel Core i7-12700H (14-core)',
      'RAM': '16GB DDR5',
      'Storage': '512GB NVMe SSD (M.2 slot)',
      'GPU': 'NVIDIA RTX 3060 6GB',
      'Battery': '90Wh, ~5-6h gaming',
      'Weight': '2.2kg',
      'OS': 'Windows 11 Home',
    },
    warranty: '2 years ASUS Kenya warranty',
    requiresInstallation: false,
    seller: sellers[2],
    tags: ['Gaming', 'RTX 3060', 'i7-12700H', '144Hz', 'MIL-SPEC'],
    bnplAvailable: true,
    monthlyInstallment: 9167,
    isFeatured: true,
    isTrending: true,
    deliveryDays: '2-4 business days',
  },
  {
    id: '22',
    name: 'Dell Inspiron 15 3520',
    slug: 'dell-inspiron-15-3520',
    brand: 'Dell',
    category: 'laptops',
    price: 52999,
    originalPrice: 64999,
    discount: 18,
    images: [
      'https://images.unsplash.com/photo-1484788984921-03950022c38b?w=600&auto=format&q=80',
    ],
    rating: 4.3,
    reviewCount: 328,
    inStock: true,
    stockCount: 35,
    description: "Dell Inspiron 15 3520 is the perfect entry-level work and study laptop for Kenyan students. Intel Core i3 12th Gen, a vibrant FHD display, and Dell's legendary reliability — all at an accessible price.",
    features: [
      'Intel Core i3-1215U 12th Gen',
      '15.6" FHD WVA anti-glare display',
      '8GB DDR4 RAM, 256GB SSD',
      'Windows 11 Home pre-installed',
      'HD webcam with noise-cancelling mic',
      'Dell Mobile Connect for smartphone sync',
    ],
    specifications: {
      'Display': '15.6" FHD (1920×1080) WVA',
      'Processor': 'Intel Core i3-1215U (12th Gen)',
      'RAM': '8GB DDR4',
      'Storage': '256GB SSD',
      'Graphics': 'Intel UHD Graphics',
      'Battery': '54Wh, ~7h',
      'Weight': '1.83kg',
      'Ports': 'USB-C, USB-A×3, HDMI, SD card, 3.5mm',
      'OS': 'Windows 11 Home',
    },
    warranty: '1 year Dell Kenya warranty',
    requiresInstallation: false,
    seller: sellers[1],
    tags: ['Student Laptop', 'i3 12th Gen', 'Windows 11', 'Budget', 'Dell'],
    bnplAvailable: true,
    monthlyInstallment: 4417,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-3 business days',
  },

  // ─── Additional Televisions ───────────────────────────────────────────────
  {
    id: '23',
    name: 'LG OLED 55" C3 4K Smart TV',
    slug: 'lg-oled-55-c3-4k',
    brand: 'LG',
    category: 'televisions',
    price: 149999,
    originalPrice: 179999,
    discount: 17,
    images: [
      'https://images.unsplash.com/photo-1571415060716-baff7991ddc3?w=600&auto=format&q=80',
    ],
    rating: 4.9,
    reviewCount: 112,
    inStock: true,
    stockCount: 5,
    description: 'LG OLED C3 is the world\'s best TV for home cinema. Each pixel self-lights for perfect blacks and infinite contrast. The α9 Gen6 AI processor and Dolby Vision IQ deliver a true cinema experience at home.',
    features: [
      'Self-lit OLED pixels – perfect blacks & contrast',
      'α9 Gen6 AI Processor 4K',
      'Dolby Vision IQ + Dolby Atmos',
      'webOS 23 with ThinQ AI',
      'HDMI 2.1 × 4 – 4K@120Hz & VRR for gaming',
      'Gallery design – ultra-slim profile',
    ],
    specifications: {
      'Screen Size': '55"',
      'Panel': 'OLED evo',
      'Resolution': '4K UHD (3840×2160)',
      'HDR': 'Dolby Vision IQ, HDR10, HLG',
      'Smart Platform': 'webOS 23',
      'HDMI': '4× HDMI 2.1',
      'Audio': '60W, Dolby Atmos',
      'Gaming': 'G-Sync, FreeSync, 4K@120Hz',
      'Dimensions (no stand)': '122×71×2.3cm',
    },
    warranty: '2 years LG Kenya warranty + free installation',
    requiresInstallation: true,
    installationFee: 0,
    seller: sellers[1],
    tags: ['OLED', '4K', 'Dolby Vision', 'HDMI 2.1', 'Gaming TV', 'Premium'],
    bnplAvailable: true,
    monthlyInstallment: 12500,
    isFeatured: true,
    isTrending: true,
    deliveryDays: '3-5 business days',
  },
  {
    id: '24',
    name: 'Sony Bravia 50" X80L 4K Smart TV',
    slug: 'sony-bravia-50-x80l-4k',
    brand: 'Sony',
    category: 'televisions',
    price: 69999,
    originalPrice: 84999,
    discount: 18,
    images: [
      'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&q=80',
    ],
    rating: 4.6,
    reviewCount: 154,
    inStock: true,
    stockCount: 12,
    description: 'Sony Bravia X80L runs Google TV for seamless content discovery across all your streaming apps. The X1 4K HDR processor delivers crisp, vivid picture quality, and BRAVIA CORE comes preloaded.',
    features: [
      'X1 4K HDR Processor',
      'Google TV – one home screen for all apps',
      'Dolby Vision & Dolby Atmos',
      'BRAVIA CORE streaming service included',
      'Voice remote with Google Assistant & Alexa',
      'TRILUMINOS PRO display technology',
    ],
    specifications: {
      'Screen Size': '50"',
      'Resolution': '4K UHD',
      'Panel': 'LED',
      'HDR': 'Dolby Vision, HDR10, HLG',
      'Smart Platform': 'Google TV',
      'Audio': '20W, Dolby Atmos',
      'HDMI': '4 (1× HDMI 2.1 eARC)',
      'USB': '2',
    },
    warranty: '2 years Sony Kenya warranty',
    requiresInstallation: true,
    installationFee: 500,
    seller: sellers[2],
    tags: ['Google TV', '4K', 'Dolby Vision', 'Sony', 'BRAVIA CORE'],
    bnplAvailable: true,
    monthlyInstallment: 5833,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-4 business days',
  },

  // ─── Additional Fridges ───────────────────────────────────────────────────
  {
    id: '25',
    name: 'Samsung 350L Side-by-Side Fridge',
    slug: 'samsung-350l-side-by-side-fridge',
    brand: 'Samsung',
    category: 'fridges',
    price: 79999,
    originalPrice: 94999,
    discount: 16,
    images: [
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&auto=format&q=80',
    ],
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    stockCount: 8,
    description: 'Samsung 350L Side-by-Side refrigerator with SpaceMax technology gives you more usable space in a slimmer body. Twin Cooling Plus keeps food fresh longer by maintaining optimal humidity in each compartment.',
    features: [
      'Twin Cooling Plus – independent cooling circuits',
      'SpaceMax Technology – more space, slim body',
      'All-around Cooling for even temperature',
      'Power Cool & Power Freeze modes',
      'Deodorizer filter for odour elimination',
      'A+ energy rating',
    ],
    specifications: {
      'Capacity': '350L (190L fridge + 160L freezer)',
      'Type': 'Side-by-Side',
      'Energy': 'A+',
      'Compressor': 'Digital Inverter',
      'Colors': 'Clean Steel / Black Caviar',
      'Dimensions': '91.2×67.5×178cm',
      'Weight': '95kg',
    },
    warranty: '1 year parts & labor, 20 years compressor warranty',
    requiresInstallation: true,
    installationFee: 2000,
    seller: sellers[0],
    tags: ['Side-by-Side', 'Twin Cooling', 'SpaceMax', 'Inverter', 'Large'],
    bnplAvailable: true,
    monthlyInstallment: 6667,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '3-5 business days',
  },
  {
    id: '26',
    name: 'Von Hotpoint 214L Double Door Fridge',
    slug: 'von-hotpoint-214l-double-door',
    brand: 'Von',
    category: 'fridges',
    price: 28999,
    originalPrice: 34999,
    discount: 17,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&q=80',
    ],
    rating: 4.3,
    reviewCount: 267,
    inStock: true,
    stockCount: 24,
    description: 'Von Hotpoint 214L double door fridge is the most popular family fridge in Kenya. Reliable Kenyan-market inverter compressor, frost-free operation, and a price point that suits every household budget.',
    features: [
      'Frost-free operation – no manual defrosting',
      'Inverter compressor for energy savings',
      'Adjustable glass shelves',
      'Crisper drawer for fresh vegetables',
      'Door alarm for safety',
      'Low noise – under 43dB',
    ],
    specifications: {
      'Capacity': '214L (155L fridge + 59L freezer)',
      'Type': 'Top-mount double door',
      'Energy': 'A',
      'Compressor': 'Inverter',
      'Colors': 'Silver',
      'Dimensions': '55.5×57×144cm',
      'Weight': '48kg',
    },
    warranty: '1 year Von Kenya warranty',
    requiresInstallation: true,
    installationFee: 1500,
    seller: sellers[3],
    tags: ['Frost-free', 'Inverter', 'Family Fridge', 'Kenya Brand', 'Budget'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-4 business days',
  },
  {
    id: '27',
    name: 'Hisense 205L Single Door Fridge',
    slug: 'hisense-205l-single-door',
    brand: 'Hisense',
    category: 'fridges',
    price: 17999,
    originalPrice: 22999,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&auto=format&q=80',
    ],
    rating: 4.1,
    reviewCount: 431,
    inStock: true,
    stockCount: 52,
    description: 'Hisense 205L single door refrigerator – perfect for singles, studios, and small families. Compact yet spacious with a built-in freezer compartment, quiet operation, and excellent energy efficiency.',
    features: [
      '205L total capacity with freezer section',
      'Multi-air flow cooling system',
      'Bright LED interior lighting',
      'Adjustable shelves for flexible storage',
      'Low-voltage start: works on 170V-220V',
      'Compact design fits small kitchens',
    ],
    specifications: {
      'Capacity': '205L',
      'Type': 'Single door with freezer box',
      'Voltage': '170V–240V',
      'Climate Class': 'N/ST',
      'Colors': 'Silver / White',
      'Dimensions': '55×57×130cm',
      'Weight': '38kg',
    },
    warranty: '1 year Hisense Kenya warranty',
    requiresInstallation: false,
    seller: sellers[3],
    tags: ['Single Door', 'Compact', 'Studio Fridge', 'Budget', 'Low Voltage'],
    bnplAvailable: false,
    isFlashSale: true,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-3 business days',
  },

  // ─── Additional Washing Machines ──────────────────────────────────────────
  {
    id: '28',
    name: 'Samsung 7KG Top Load Washing Machine',
    slug: 'samsung-7kg-top-load',
    brand: 'Samsung',
    category: 'washing-machines',
    price: 34999,
    originalPrice: 42999,
    discount: 19,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&q=80',
    ],
    rating: 4.4,
    reviewCount: 219,
    inStock: true,
    stockCount: 29,
    description: 'Samsung 7KG top load washing machine with Magic Dispenser automatically releases detergent at the right time for every wash. Digital Inverter Motor is quieter, more efficient, and covered by a 10-year warranty.',
    features: [
      'Magic Dispenser – auto detergent release',
      'Digital Inverter Motor – 10-year warranty',
      'Wobble Pulsator for gentle yet effective wash',
      'Child Lock for household safety',
      '700 RPM spin speed',
      'Quick Wash – full load in 15 minutes',
    ],
    specifications: {
      'Capacity': '7kg',
      'Type': 'Top Load',
      'Spin Speed': '700 RPM',
      'Programs': '8',
      'Motor': 'Digital Inverter',
      'Dimensions': '54.5×54.5×91cm',
      'Weight': '35kg',
    },
    warranty: '2 years parts & labor, 10 years motor warranty',
    requiresInstallation: true,
    installationFee: 1500,
    seller: sellers[0],
    tags: ['Top Load', 'Inverter Motor', '7KG', 'Quick Wash', 'Samsung'],
    bnplAvailable: true,
    monthlyInstallment: 2917,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '3-5 business days',
  },
  {
    id: '29',
    name: 'Beko 8KG Front Load Washing Machine',
    slug: 'beko-8kg-front-load',
    brand: 'Beko',
    category: 'washing-machines',
    price: 52999,
    originalPrice: 64999,
    discount: 18,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&q=80',
    ],
    rating: 4.5,
    reviewCount: 134,
    inStock: true,
    stockCount: 14,
    description: 'Beko 8KG front load washer with SteamCure technology removes 99.9% of bacteria and allergens without detergent. StainExpert program tackles 24 different stain types — perfect for active Kenyan families.',
    features: [
      'SteamCure – kills 99.9% of bacteria & allergens',
      'StainExpert – 24 stain programs',
      'ProSmart Inverter Motor – quiet & durable',
      '1200 RPM high-efficiency spin',
      'AquaTech washing – clean in 59 minutes',
      'Child Lock + delay start timer',
    ],
    specifications: {
      'Capacity': '8kg',
      'Type': 'Front Load',
      'Spin Speed': '1200 RPM',
      'Energy': 'A+++',
      'Programs': '16',
      'Motor': 'ProSmart Inverter',
      'Dimensions': '60×49×84cm',
      'Weight': '65kg',
    },
    warranty: '2 years Beko Kenya warranty',
    requiresInstallation: true,
    installationFee: 2000,
    seller: sellers[1],
    tags: ['Front Load', 'SteamCure', '8KG', 'A+++', 'Anti-Allergy'],
    bnplAvailable: true,
    monthlyInstallment: 4417,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '3-5 business days',
  },

  // ─── Additional Cookers ───────────────────────────────────────────────────
  {
    id: '30',
    name: 'Ramtons 3-Burner Gas + Electric Cooker',
    slug: 'ramtons-3-burner-gas-electric',
    brand: 'Ramtons',
    category: 'cookers',
    price: 12999,
    originalPrice: 16999,
    discount: 24,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&q=80',
    ],
    rating: 4.2,
    reviewCount: 389,
    inStock: true,
    stockCount: 61,
    description: 'Ramtons 3-burner combination cooker with 2 gas burners + 1 electric hotplate gives you the versatility to cook with gas or electricity. The built-in oven and grill makes it a complete kitchen solution.',
    features: [
      '2 gas burners + 1 electric hotplate',
      '50L electric oven with grill function',
      'Auto-ignition on gas burners',
      'Safety thermostat on oven',
      'Tempered glass lid',
      'Available for LPG and natural gas',
    ],
    specifications: {
      'Burners': '2 gas + 1 electric hotplate',
      'Oven': '50L electric with grill',
      'Ignition': 'Auto-electric',
      'Fuel': 'LPG / Natural Gas',
      'Width': '55cm',
      'Material': 'Stainless steel top',
    },
    warranty: '1 year Ramtons Kenya warranty',
    requiresInstallation: true,
    installationFee: 1000,
    seller: sellers[3],
    tags: ['Gas + Electric', '3 Burner', 'Combination Cooker', 'Budget', 'Oven'],
    bnplAvailable: false,
    isFlashSale: true,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-4 business days',
  },
  {
    id: '31',
    name: 'Mika 60cm 4-Burner Electric Cooker',
    slug: 'mika-60cm-4-burner-electric',
    brand: 'Mika',
    category: 'cookers',
    price: 26999,
    originalPrice: 32999,
    discount: 18,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&q=80',
    ],
    rating: 4.3,
    reviewCount: 198,
    inStock: true,
    stockCount: 33,
    description: 'Mika 60cm 4-burner electric cooker with ceramic glass hob offers a modern, easy-clean cooking surface. The 65L fan-assisted oven ensures even heat distribution for perfect baking every time.',
    features: [
      '4 ceramic glass electric hotplates',
      '65L fan-assisted electric oven',
      'Residual heat indicators for safety',
      'Digital timer with auto shut-off',
      'Child lock for kitchen safety',
      'Easy-clean smooth ceramic surface',
    ],
    specifications: {
      'Burners': '4 ceramic glass electric',
      'Oven': '65L fan-assisted',
      'Hob Type': 'Ceramic glass',
      'Power': '6500W total',
      'Width': '60cm',
      'Control': 'Touch + knob hybrid',
    },
    warranty: '1 year Mika warranty',
    requiresInstallation: true,
    installationFee: 1500,
    seller: sellers[1],
    tags: ['Electric', '4 Burner', 'Ceramic', 'Fan Oven', 'Modern'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-4 business days',
  },

  // ─── Additional Audio ─────────────────────────────────────────────────────
  {
    id: '32',
    name: 'Samsung Galaxy Buds2 Pro',
    slug: 'samsung-galaxy-buds2-pro',
    brand: 'Samsung',
    category: 'audio',
    price: 17999,
    originalPrice: 22999,
    discount: 22,
    images: [
      'https://images.unsplash.com/photo-1590658006821-04f4008d5717?w=600&auto=format&q=80',
    ],
    rating: 4.6,
    reviewCount: 287,
    inStock: true,
    stockCount: 34,
    description: 'Samsung Galaxy Buds2 Pro deliver Hi-Fi 24-bit audio and intelligent ANC that adapts to your environment. Seamless integration with Samsung Galaxy devices and 360 Audio immersive sound stage.',
    features: [
      'Intelligent ANC – blocks 98% of noise',
      'Hi-Fi 24-bit audio (Samsung devices)',
      '360 Audio with head-tracking',
      'Auto Switch between Galaxy devices',
      '8h battery + 29h with case',
      'IPX7 water resistance',
    ],
    specifications: {
      'Driver': '10mm two-way speaker',
      'ANC': 'Intelligent ANC',
      'Battery': '5h + 18h case = 23h (ANC off)',
      'Bluetooth': '5.3',
      'Water': 'IPX7 earbuds, IPX2 case',
      'Weight': '5.5g per earbud',
      'Codecs': 'SSC, AAC, SBC',
    },
    warranty: '1 year Samsung Kenya warranty',
    requiresInstallation: false,
    seller: sellers[0],
    tags: ['ANC', 'Hi-Fi', '360 Audio', 'Samsung Ecosystem', 'IPX7'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: true,
    deliveryDays: '1-2 business days',
  },
  {
    id: '33',
    name: 'Anker Soundcore Life Q35',
    slug: 'anker-soundcore-life-q35',
    brand: 'Anker',
    category: 'audio',
    price: 7999,
    originalPrice: 10999,
    discount: 27,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&q=80',
    ],
    rating: 4.4,
    reviewCount: 623,
    inStock: true,
    stockCount: 88,
    description: 'Anker Soundcore Life Q35 offers multi-mode ANC in an ultra-affordable package. LDAC Hi-Res wireless audio and 40-hour battery life make it the unbeatable headphone value under KES 10,000 in Kenya.',
    features: [
      'Multi-mode ANC (Transport, Outdoor, Indoor)',
      'LDAC Hi-Res Wireless Audio certified',
      '40-hour battery with ANC on',
      'Custom EQ via Soundcore app',
      'Foldable design for portability',
      'Built-in Alexa voice assistant',
    ],
    specifications: {
      'Driver': '40mm',
      'ANC': 'Multi-mode hybrid ANC',
      'Battery': '40h (ANC on), 60h (off)',
      'Quick Charge': '5 min → 4h',
      'Bluetooth': '5.0, LDAC/AAC/SBC',
      'Weight': '260g',
      'Foldable': 'Yes',
    },
    warranty: '18 months Anker warranty',
    requiresInstallation: false,
    seller: sellers[2],
    tags: ['ANC', 'LDAC', '40h Battery', 'Budget', 'Hi-Res Audio'],
    bnplAvailable: false,
    isFlashSale: true,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-3 business days',
  },

  // ─── Additional Tablets ───────────────────────────────────────────────────
  {
    id: '34',
    name: 'Apple iPad 10th Generation',
    slug: 'apple-ipad-10th-gen',
    brand: 'Apple',
    category: 'tablets',
    price: 59999,
    originalPrice: 69999,
    discount: 14,
    images: [
      'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=600&auto=format&q=80',
    ],
    rating: 4.8,
    reviewCount: 198,
    inStock: true,
    stockCount: 16,
    description: 'The 10th-generation iPad with the A14 Bionic chip is the most capable iPad ever at this price. A10.9" Liquid Retina display, 12MP front camera in landscape, and USB-C make it perfect for work and creativity.',
    features: [
      'A14 Bionic chip – neural engine AI',
      '10.9" Liquid Retina display, 500 nits',
      '12MP ultrawide front camera in landscape',
      'USB-C connectivity with 2× faster transfer',
      'Wi-Fi 6 + optional 5G cellular',
      'Compatible with Apple Pencil (1st gen)',
    ],
    specifications: {
      'Display': '10.9" Liquid Retina (2360×1640)',
      'Chip': 'A14 Bionic',
      'Storage': '64GB / 256GB',
      'Camera': '12MP rear, 12MP ultrawide front',
      'Battery': 'Up to 10h',
      'Connectivity': 'Wi-Fi 6, USB-C, Bluetooth 5.2',
      'OS': 'iPadOS 16',
      'Weight': '477g',
    },
    warranty: '1 year Apple Kenya warranty',
    requiresInstallation: false,
    seller: sellers[4],
    tags: ['A14 Bionic', 'Liquid Retina', 'USB-C', 'iPadOS', 'Apple Pencil'],
    bnplAvailable: true,
    monthlyInstallment: 5000,
    isFeatured: true,
    isTrending: false,
    deliveryDays: '1-2 business days',
  },
  {
    id: '35',
    name: 'Lenovo Tab P11 Plus Gen 2',
    slug: 'lenovo-tab-p11-plus-gen2',
    brand: 'Lenovo',
    category: 'tablets',
    price: 28999,
    originalPrice: 35999,
    discount: 19,
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&auto=format&q=80',
    ],
    rating: 4.3,
    reviewCount: 156,
    inStock: true,
    stockCount: 22,
    description: 'Lenovo Tab P11 Plus Gen 2 with a vivid 11.5" 2K display and MediaTek Helio G99 is the best Android tablet value in Kenya. Great for students, streaming, and light productivity with keyboard support.',
    features: [
      '11.5" 2K (2000×1200) display, 400 nits',
      'MediaTek Helio G99 octa-core processor',
      '7700mAh long-life battery (up to 12h)',
      'Quad JBL speakers with Dolby Atmos',
      'Optional keyboard cover attachment',
      'Face unlock + rear fingerprint sensor',
    ],
    specifications: {
      'Display': '11.5" 2K IPS (2000×1200) 60Hz',
      'Processor': 'MediaTek Helio G99',
      'RAM': '6GB',
      'Storage': '128GB + microSD',
      'Camera': '13MP rear, 8MP front',
      'Battery': '7700mAh',
      'OS': 'Android 12L',
      'Weight': '520g',
    },
    warranty: '1 year Lenovo Kenya warranty',
    requiresInstallation: false,
    seller: sellers[1],
    tags: ['2K Display', 'JBL Speakers', 'Dolby Atmos', 'Student Tablet', 'Android'],
    bnplAvailable: false,
    isFeatured: false,
    isTrending: false,
    deliveryDays: '2-3 business days',
  },
]

export const reviews: Review[] = [
  { id: 'r1', productId: '1', author: 'David M.', location: 'Nairobi', rating: 5, title: 'Best Android phone I\'ve ever owned', body: 'The camera is insane. 100× zoom is not a gimmick. The S Pen makes this a real productivity tool. M-PESA integration on Samsung Pay works flawlessly.', date: '2024-03-12', verified: true, helpful: 34 },
  { id: 'r2', productId: '1', author: 'Amina K.', location: 'Mombasa', rating: 4, title: 'Excellent phone, slightly heavy', body: 'Screen quality is unmatched. Battery lasts me through the day easily. Only complaint is the weight – it\'s a bit heavy for one-handed use.', date: '2024-02-28', verified: true, helpful: 18 },
  { id: 'r3', productId: '4', author: 'Brian O.', location: 'Kisumu', rating: 5, title: 'MacBook Air is worth every shilling', body: 'I run heavy design projects on this with zero fan noise. Battery honestly lasts 15+ hours of real work. The M3 chip is incredibly fast.', date: '2024-03-01', verified: true, helpful: 27 },
  { id: 'r4', productId: '6', author: 'Mary W.', location: 'Nakuru', rating: 5, title: 'Picture quality is stunning', body: 'The QLED colors are vibrant without being over-saturated. Setup was easy and the Samsung support team came for installation on time. Very happy!', date: '2024-02-15', verified: true, helpful: 21 },
  { id: 'r5', productId: '11', author: 'Tom N.', location: 'Thika', rating: 5, title: 'These headphones are genuinely magical', body: 'The noise cancellation blocks out matatu noise completely. I use them for morning commute and can finally focus. Best purchase this year.', date: '2024-03-20', verified: true, helpful: 45 },
]

export const mockOrders: Order[] = [
  {
    id: 'ORD-2024-001',
    customerName: 'Sarah Wanjiku',
    customerPhone: '+254 712 345 678',
    items: [
      { productId: '1', name: 'Samsung Galaxy S24 Ultra', quantity: 1, price: 139999, image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=200&auto=format&q=80' },
    ],
    total: 139999,
    status: 'delivered',
    paymentMethod: 'mpesa',
    paymentStatus: 'paid',
    deliveryAddress: '14 Hurlingham Road, Nairobi',
    county: 'Nairobi',
    createdAt: '2024-03-18T09:30:00Z',
    mpesaRef: 'QGH7R4KLMN',
    courierName: 'G4S Courier',
    trackingNumber: 'G4S-2024-44521',
  },
  {
    id: 'ORD-2024-002',
    customerName: 'Brian Ochieng',
    customerPhone: '+254 722 876 543',
    items: [
      { productId: '12', name: 'JBL Charge 5', quantity: 1, price: 11999, image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=200&auto=format&q=80' },
      { productId: '14', name: 'Apple AirPods Pro 2', quantity: 1, price: 29999, image: 'https://images.unsplash.com/photo-1590658006821-04f4008d5717?w=200&auto=format&q=80' },
    ],
    total: 41998,
    status: 'shipped',
    paymentMethod: 'mpesa',
    paymentStatus: 'paid',
    deliveryAddress: 'Kisumu CBD, Oginga Odinga St',
    county: 'Kisumu',
    createdAt: '2024-03-20T14:15:00Z',
    mpesaRef: 'RKL9P2WXYZ',
    courierName: 'Fargo Courier',
    trackingNumber: 'FRG-2024-88932',
  },
  {
    id: 'ORD-2024-003',
    customerName: 'Mercy Achieng',
    customerPhone: '+254 733 222 111',
    items: [
      { productId: '5', name: 'HP Pavilion 15', quantity: 1, price: 64999, image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=200&auto=format&q=80' },
    ],
    total: 64999,
    status: 'processing',
    paymentMethod: 'bnpl',
    paymentStatus: 'paid',
    deliveryAddress: 'Westlands, Ring Road',
    county: 'Nairobi',
    createdAt: '2024-03-21T10:00:00Z',
  },
  {
    id: 'ORD-2024-004',
    customerName: 'John Kamau',
    customerPhone: '+254 700 111 222',
    items: [
      { productId: '8', name: 'LG 385L Fridge', quantity: 1, price: 54999, image: 'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=200&auto=format&q=80' },
    ],
    total: 54999,
    status: 'confirmed',
    paymentMethod: 'mpesa',
    paymentStatus: 'paid',
    deliveryAddress: 'Kitengela, Namanga Road',
    county: 'Kajiado',
    createdAt: '2024-03-22T16:45:00Z',
    mpesaRef: 'VYX3M8QRST',
  },
  {
    id: 'ORD-2024-005',
    customerName: 'Grace Njeri',
    customerPhone: '+254 711 444 333',
    items: [
      { productId: '4', name: 'MacBook Air M3', quantity: 1, price: 159999, image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=200&auto=format&q=80' },
    ],
    total: 159999,
    status: 'pending',
    paymentMethod: 'card',
    paymentStatus: 'pending',
    deliveryAddress: 'Karen, Langata Road',
    county: 'Nairobi',
    createdAt: '2024-03-22T18:00:00Z',
  },
]

export const flashSaleProducts = products.filter((p) => p.isFlashSale)
export const featuredProducts = products.filter((p) => p.isFeatured)
export const trendingProducts = products.filter((p) => p.isTrending)

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter((p) => p.id !== product.id && (p.category === product.category || p.brand === product.brand))
    .slice(0, limit)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  )
}
